[[bundle]] # Must have at least one bundle.
  name = "asset1.js" # Must have file extension
  assets = ["/users/user.js", "http://mycdn.com/jquery.js", "bootstrap.js"] # array of resolvable resource names

[[bundle]] # Second bundle
  name = "asset2.css"
  assets = ["bootstrap", "/app/app.css"] # If there is no extension, the one from the name is used

[options.coffee] # Options for the processor with the alias "coffee"
  BARE = true

[options.pipeline]  # Options for the humpty pipeline itself
  mode = "DEVELOPMENT" # Defaults to "PRODUCTION"
  
  
[options.pipeline.elements] # Arrays of names of pipeline elements to use, in the given order
  sources = [] 
  assets = []
  bundles = []
